apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configMapGenerator:
  - name: bidding-config
    envs: [.env]

secretGenerator:
  - name: bidding-secrets
    envs: [.env]

resources:
  - db/postgres-service.yaml
  - db/postgres-db.yaml
  - cache/redis-service.yaml
  - cache/redis-db.yaml
  - app/service.yaml
  - app/deployment.yaml
  - app/ingress.yaml